# Introduction to NumPy
Plan:
- Creating arrays
- Multi-dimensional arrays
- Randomly generated arrays
- Element-wise operations
    - Comparison operations
    - Logical operations
- Summarizing operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/andre/anaconda3/envs/exp-tracking-env/lib/python3.9/site-packages/numpy/__init__.py'>

### Creating Arrays

In [3]:
# Create an array of 10 zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# Fill array with arbitrary numbers
# np.full(n, m)
#   n: number of elements
#   m: value to use 
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
# Converting existing python list to numpy array
arr = [1, 2, 3, 5, 7, 12]
a = np.array(arr)
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
# Get element by index
a[2]

3

In [8]:
# Replace value
a[2] = 10

In [9]:
# Create range from 0-9 (10 is exclusive)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Create range from 3-9 (10 is exclusive)
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
# Creates array with number between the parameters given, and the last one is the amount
# np.linspace(start, stop, steps)
#   start: value to start with
#   stop: value to end with
#   steps: number of values to return
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi-Dimensional Arrays

In [12]:
# Add a tuple in to create an array of the size rows x columns
# np.zeros((n, m))
#   n: number of rows
#   m: number of columns
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
# Create 2D array
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [14]:
# Access elements with tuple index
n[0][1]

2

In [15]:
# Reassign elements with tuple index
n[0][1] = 20

In [16]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
# Want to get whole row
n[0]

array([ 1, 20,  3])

In [18]:
# Ovewrite whole row
n[2] = [1, 1, 1]

In [19]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [20]:
# Get the column - get all the rows, but just index one
n[:, 1]

array([20,  5,  1])

In [21]:
# Gets every row
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
# Reassign the whole column - get all the rows, but just index one
n[:, 1] = [0, 1, 2]

In [23]:
n

array([[1, 0, 3],
       [4, 1, 6],
       [1, 2, 1]])

### Randomly generated arrays

In [24]:
# Gets random numbers of size row x columns
# np.random.rand((n, m))
#   n: number of rows
#   m: number of columns
np.random.rand(5,2)

# Actually only pseudo-random. Can seed this in advance

array([[0.51379367, 0.55641525],
       [0.73386525, 0.72566319],
       [0.02772362, 0.37347856],
       [0.72043834, 0.43690245],
       [0.37460017, 0.79238839]])

In [25]:
# Seeding random.rand. Will be the same every time (at least in the same environment)
np.random.seed(2)
np.random.rand(5,2)


array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [26]:
# Generate numbers from the standard normal distribution
# Gets random numbers of size row x columns
# np.random.randn((n, m))
#   n: number of rows
#   m: number of columns
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [27]:
# To scale numbers up, multiply by the number you want the max to be
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [28]:
# Generate array of integers
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operations

In [29]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [30]:
# Say we want to add 1 to every element of this array
a + 1

# Would not work in vanilla python. Would require a loop to add to each

array([1, 2, 3, 4, 5])

In [31]:
# Same thing except for doubling
a * 2

array([0, 2, 4, 6, 8])

In [32]:
# Can chain these operations
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [33]:
# Can do element-wise operations
a + b

# Adds each array element, element-wise

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [34]:
# Can chain it any way we want
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

### Comparison Operators

In [35]:
a

array([0, 1, 2, 3, 4])

In [36]:
# See which elements are greater than or equal to 2
a >= 2

array([False, False,  True,  True,  True])

In [37]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [38]:
# See which elements of a are greater than b
a > b

array([False, False,  True,  True,  True])

In [39]:
# a > b returns a boolean array like the above cell, giving the elements of a where the condition is true.
#   Passing this to a will return only those values
a[a > b]

array([2, 3, 4])

### Summarizing operations

In [40]:
a

array([0, 1, 2, 3, 4])

In [41]:
# Returns smallest value
a.min()

0

In [42]:
# Returns largest value
a.max()

4

In [43]:
# Returns sum of values
a.sum()

10

In [44]:
# Returns average of values
a.mean()

2.0

In [45]:
# Returns standard deviation of values
a.std()

1.4142135623730951